-- 045 source lists, batch 5 (oxjob #1615; Jason OK 2026-10-09): national
-- research-evaluation registers (Russia, Poland, Flanders, Turkey, South Africa,
-- Italy, Korea, Spain, Argentina, Colombia), business-school lists (FNEGE, FT50,
-- UTD24) and the China Computer Federation journal list. Same conventions as
-- 040/041: one list per level, ids and display names keep the maintainer's own
-- level labels, and the scope text says which level is the top one. Non-normative
-- throughout ("appears on", never "recommended by us").
--
-- Licences: Publindex's open dataset is CC BY-SA 4.0; KCI's open API is "no
-- restriction on use"; the others state no data licence. Same handling as JUFO:
-- maintainer + URL credited on the entity doc, GUI and help center.

INSERT INTO source_list (id, display_name, maintainer, url, scope) VALUES
  ('russia-white-list-1', 'Russian White List, level 1',
   'Russian Center for Scientific Information (RCSI), for the Ministry of Science and Higher Education of Russia',
   'https://journalrank.rcsi.science/',
   'Journals at level 1 (the top level) of the White List of scientific journals, the national journal list used in Russian research evaluation, all fields.'),
  ('russia-white-list-2', 'Russian White List, level 2',
   'Russian Center for Scientific Information (RCSI), for the Ministry of Science and Higher Education of Russia',
   'https://journalrank.rcsi.science/',
   'Journals at level 2 (second of four levels) of the White List of scientific journals, the national journal list used in Russian research evaluation, all fields.'),
  ('russia-white-list-3', 'Russian White List, level 3',
   'Russian Center for Scientific Information (RCSI), for the Ministry of Science and Higher Education of Russia',
   'https://journalrank.rcsi.science/',
   'Journals at level 3 (third of four levels) of the White List of scientific journals, the national journal list used in Russian research evaluation, all fields.'),
  ('russia-white-list-4', 'Russian White List, level 4',
   'Russian Center for Scientific Information (RCSI), for the Ministry of Science and Higher Education of Russia',
   'https://journalrank.rcsi.science/',
   'Journals at level 4 (fourth of four levels) of the White List of scientific journals, the national journal list used in Russian research evaluation, all fields.'),

  ('poland-200', 'Polish journal list, 200 points',
   'Ministry of Science and Higher Education of Poland',
   'https://www.gov.pl/web/nauka/nowy-wykaz-czasopism-naukowych-i-recenzowanych-materialow-z-konferencji-miedzynarodowych',
   'Journals worth 200 points (the top level) on the Polish Ministry of Science list of scientific journals, used in Polish research evaluation, all fields.'),
  ('poland-140', 'Polish journal list, 140 points',
   'Ministry of Science and Higher Education of Poland',
   'https://www.gov.pl/web/nauka/nowy-wykaz-czasopism-naukowych-i-recenzowanych-materialow-z-konferencji-miedzynarodowych',
   'Journals worth 140 points (second of six levels) on the Polish Ministry of Science list of scientific journals, used in Polish research evaluation, all fields.'),
  ('poland-100', 'Polish journal list, 100 points',
   'Ministry of Science and Higher Education of Poland',
   'https://www.gov.pl/web/nauka/nowy-wykaz-czasopism-naukowych-i-recenzowanych-materialow-z-konferencji-miedzynarodowych',
   'Journals worth 100 points (third of six levels) on the Polish Ministry of Science list of scientific journals, used in Polish research evaluation, all fields.'),
  ('poland-70', 'Polish journal list, 70 points',
   'Ministry of Science and Higher Education of Poland',
   'https://www.gov.pl/web/nauka/nowy-wykaz-czasopism-naukowych-i-recenzowanych-materialow-z-konferencji-miedzynarodowych',
   'Journals worth 70 points (fourth of six levels) on the Polish Ministry of Science list of scientific journals, used in Polish research evaluation, all fields.'),
  ('poland-40', 'Polish journal list, 40 points',
   'Ministry of Science and Higher Education of Poland',
   'https://www.gov.pl/web/nauka/nowy-wykaz-czasopism-naukowych-i-recenzowanych-materialow-z-konferencji-miedzynarodowych',
   'Journals worth 40 points (fifth of six levels) on the Polish Ministry of Science list of scientific journals, used in Polish research evaluation, all fields.'),
  ('poland-20', 'Polish journal list, 20 points',
   'Ministry of Science and Higher Education of Poland',
   'https://www.gov.pl/web/nauka/nowy-wykaz-czasopism-naukowych-i-recenzowanych-materialow-z-konferencji-miedzynarodowych',
   'Journals worth 20 points (sixth of six levels) on the Polish Ministry of Science list of scientific journals, used in Polish research evaluation, all fields.'),

  ('vabb-shw', 'VABB-SHW (Flanders)',
   'ECOOM, University of Antwerp, for the Flemish government',
   'https://www.ecoom.be/nodes/tijdschrifteninvabbshwversie1520142023/en',
   'Journals in the Flemish Academic Bibliography for the Social Sciences and Humanities (VABB-SHW): journals whose articles count as peer-reviewed in the Flemish university funding model.'),

  ('fnege-1-star', 'FNEGE journal ranking, 1*',
   'FNEGE (Fondation Nationale pour l''Enseignement de la Gestion des Entreprises)',
   'https://fnege.org/classement-des-revues-scientifiques-en-sciences-de-gestion/',
   'Journals ranked 1* (the top rank) in the FNEGE ranking of management journals (France), 2025 edition.'),
  ('fnege-1', 'FNEGE journal ranking, 1',
   'FNEGE (Fondation Nationale pour l''Enseignement de la Gestion des Entreprises)',
   'https://fnege.org/classement-des-revues-scientifiques-en-sciences-de-gestion/',
   'Journals ranked 1 (second rank, below 1*) in the FNEGE ranking of management journals (France), 2025 edition.'),
  ('fnege-2', 'FNEGE journal ranking, 2',
   'FNEGE (Fondation Nationale pour l''Enseignement de la Gestion des Entreprises)',
   'https://fnege.org/classement-des-revues-scientifiques-en-sciences-de-gestion/',
   'Journals ranked 2 (third rank) in the FNEGE ranking of management journals (France), 2025 edition.'),
  ('fnege-3', 'FNEGE journal ranking, 3',
   'FNEGE (Fondation Nationale pour l''Enseignement de la Gestion des Entreprises)',
   'https://fnege.org/classement-des-revues-scientifiques-en-sciences-de-gestion/',
   'Journals ranked 3 (fourth rank) in the FNEGE ranking of management journals (France), 2025 edition.'),
  ('fnege-4', 'FNEGE journal ranking, 4',
   'FNEGE (Fondation Nationale pour l''Enseignement de la Gestion des Entreprises)',
   'https://fnege.org/classement-des-revues-scientifiques-en-sciences-de-gestion/',
   'Journals ranked 4 (fifth rank) in the FNEGE ranking of management journals (France), 2025 edition.'),

  ('tr-dizin', 'TR Dizin',
   'TÜBİTAK ULAKBİM (Türkiye)',
   'https://search.trdizin.gov.tr/',
   'Journals on the current TR Dizin list, the national index of scholarly journals in Türkiye, all fields.'),

  ('dhet', 'DHET list of approved South African journals',
   'Department of Higher Education and Training (DHET), South Africa',
   'https://db.crest.sun.ac.za/zapublications/',
   'South African journals on the DHET list of approved journals, whose articles are eligible for research-output subsidy (file hosted by CREST, Stellenbosch University).'),

  ('ft50', 'FT50',
   'Financial Times',
   'https://www.ft.com/content/3405a512-5cbb-11e1-8f1f-00144feabdc0',
   'The 50 journals used in the Financial Times Research Rank for its business school rankings, as revised in April 2026.'),
  ('utd24', 'UTD24',
   'Naveen Jindal School of Management, University of Texas at Dallas',
   'https://jsom.utdallas.edu/the-utd-top-100-business-school-research-rankings/',
   'The 24 journals behind the UT Dallas Top 100 Business School Research Rankings.'),

  ('anvur-class-a', 'ANVUR Class A journals',
   'ANVUR (Italian National Agency for the Evaluation of Universities and Research Institutes)',
   'https://www.anvur.it/it/ricerca/riviste/elenchi-di-riviste-classificate',
   'Journals in Class A (the top tier) for at least one hiring sector in the ANVUR journal lists (Italy), areas 08 and 10-14: architecture, humanities, history, philosophy, education, psychology, law, economics and statistics, political and social sciences.'),
  ('anvur-scientific', 'ANVUR scientific journals',
   'ANVUR (Italian National Agency for the Evaluation of Universities and Research Institutes)',
   'https://www.anvur.it/it/ricerca/riviste/elenchi-di-riviste-classificate',
   'Journals rated scientific in the ANVUR journal lists (Italy), areas 08 and 10-14: architecture, humanities, history, philosophy, education, psychology, law, economics and statistics, political and social sciences. Class A journals are a subset.'),

  ('kci-excellent', 'KCI Excellent Journal',
   'National Research Foundation of Korea (NRF)',
   'https://www.kci.go.kr/',
   'Journals accredited as Excellent (the top tier) in the Korea Citation Index (KCI), Korea''s national journal accreditation, all fields.'),
  ('kci-registered', 'KCI Registered Journal',
   'National Research Foundation of Korea (NRF)',
   'https://www.kci.go.kr/',
   'Journals accredited as Registered (second of three tiers) in the Korea Citation Index (KCI), Korea''s national journal accreditation, all fields.'),
  ('kci-candidate', 'KCI Candidate Journal',
   'National Research Foundation of Korea (NRF)',
   'https://www.kci.go.kr/',
   'Journals accredited as Candidate (third of three tiers) in the Korea Citation Index (KCI), Korea''s national journal accreditation, all fields.'),

  ('ccf-a', 'CCF recommended journals, class A',
   'China Computer Federation (CCF)',
   'https://www.ccf.org.cn/Academic_Evaluation/By_category/',
   'Journals in class A (the top class) of the China Computer Federation list of recommended international journals, 7th edition (2026), computer science. Conferences on the list are not included.'),
  ('ccf-b', 'CCF recommended journals, class B',
   'China Computer Federation (CCF)',
   'https://www.ccf.org.cn/Academic_Evaluation/By_category/',
   'Journals in class B (second of three classes) of the China Computer Federation list of recommended international journals, 7th edition (2026), computer science. Conferences on the list are not included.'),
  ('ccf-c', 'CCF recommended journals, class C',
   'China Computer Federation (CCF)',
   'https://www.ccf.org.cn/Academic_Evaluation/By_category/',
   'Journals in class C (third of three classes) of the China Computer Federation list of recommended international journals, 7th edition (2026), computer science. Conferences on the list are not included.'),

  ('fecyt-seal', 'FECYT quality seal',
   'FECYT (Spanish Foundation for Science and Technology)',
   'https://calidadrevistas.fecyt.es/revistas-sello-fecyt',
   'Spanish journals currently holding the FECYT quality seal for scientific journals.'),

  ('nbra', 'Núcleo Básico de Revistas Científicas Argentinas',
   'CAICYT-CONICET (Argentina)',
   'https://www.caicyt-conicet.gov.ar/sitio/comunicacion-cientifica/nucleo-basico/revistas-integrantes/',
   'Journals in the Núcleo Básico de Revistas Científicas Argentinas (NBRA), the core set of Argentine scientific journals.'),

  ('publindex-a1', 'Publindex, A1',
   'Minciencias (Ministry of Science, Technology and Innovation of Colombia)',
   'https://minciencias.gov.co/convocatorias/convocatoria-clasificacion-y-reconocimiento-revistas-cientificas-nacionales-publindex',
   'Colombian journals classified A1 (the top category) in Publindex, the national journal index, 2026 call.'),
  ('publindex-a2', 'Publindex, A2',
   'Minciencias (Ministry of Science, Technology and Innovation of Colombia)',
   'https://minciencias.gov.co/convocatorias/convocatoria-clasificacion-y-reconocimiento-revistas-cientificas-nacionales-publindex',
   'Colombian journals classified A2 (second category) in Publindex, the national journal index, 2026 call.'),
  ('publindex-b', 'Publindex, B',
   'Minciencias (Ministry of Science, Technology and Innovation of Colombia)',
   'https://minciencias.gov.co/convocatorias/convocatoria-clasificacion-y-reconocimiento-revistas-cientificas-nacionales-publindex',
   'Colombian journals classified B (third category) in Publindex, the national journal index, 2026 call.'),
  ('publindex-c', 'Publindex, C',
   'Minciencias (Ministry of Science, Technology and Innovation of Colombia)',
   'https://minciencias.gov.co/convocatorias/convocatoria-clasificacion-y-reconocimiento-revistas-cientificas-nacionales-publindex',
   'Colombian journals classified C (fourth category) in Publindex, the national journal index, 2026 call.'),
  ('publindex-recognized', 'Publindex, recognized',
   'Minciencias (Ministry of Science, Technology and Innovation of Colombia)',
   'https://minciencias.gov.co/convocatorias/convocatoria-clasificacion-y-reconocimiento-revistas-cientificas-nacionales-publindex',
   'Colombian journals recognized in Publindex, the national journal index, 2026 call: they meet its editorial-quality standards and enter the national indexing system without a category.')
ON CONFLICT (id) DO NOTHING;
